//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPNMonClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.VPNMonServer")]
    public interface VPNMonServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VPNMonServer/keepAlive", ReplyAction="http://tempuri.org/VPNMonServer/keepAliveResponse")]
        string keepAlive(string value, string vpnAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VPNMonServer/fileCheck", ReplyAction="http://tempuri.org/VPNMonServer/fileCheckResponse")]
        bool fileCheck(string directory, string fileName, string md5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VPNMonServer/getFileString", ReplyAction="http://tempuri.org/VPNMonServer/getFileStringResponse")]
        string getFileString(string directory, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VPNMonServer/getMasterList", ReplyAction="http://tempuri.org/VPNMonServer/getMasterListResponse")]
        System.IO.Stream getMasterList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VPNMonServerChannel : VPNMonClient.ServiceReference1.VPNMonServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VPNMonServerClient : System.ServiceModel.ClientBase<VPNMonClient.ServiceReference1.VPNMonServer>, VPNMonClient.ServiceReference1.VPNMonServer {
        
        public VPNMonServerClient() {
        }
        
        public VPNMonServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VPNMonServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VPNMonServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VPNMonServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string keepAlive(string value, string vpnAddress) {
            return base.Channel.keepAlive(value, vpnAddress);
        }
        
        public bool fileCheck(string directory, string fileName, string md5) {
            return base.Channel.fileCheck(directory, fileName, md5);
        }
        
        public string getFileString(string directory, string fileName) {
            return base.Channel.getFileString(directory, fileName);
        }
        
        public System.IO.Stream getMasterList() {
            return base.Channel.getMasterList();
        }
    }
}
